apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: int-pr-fc-cumulus
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  spec:
    replicas: 1
    containers:
    - name: nginx
      image: registry.redhat.io/rhel8/nginx-118
