kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../base/

patches:
- target:
    kind: Kibana
    name: kibana-instance
  patch: |-
    - op: replace
      path: /spec/config/server.publicBaseUrl
      value: 'https://kibana-ircc-integration-elasticsearch-eck.apps.opc-hip-apps.awc.ci.gc.ca'