apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: ircc-integreation-filebeat
  namespace: ircc-integration-elasticsearch-eck
spec:
  config:
    filebeat.inputs:
    - json:
        expand_keys: true
        keys_under_root: true
      paths:
      - /var/log/containers/ircc*-int-svc*.log
      processors:
      - drop_event:
          when.not.has_fields:
          - '@timestamp'
          - message
          - service
      type: container
    - group_id: ircc-integration-filebeat
      hosts:
      - ircc-integration-kafka-cluster-kafka-brokers.ircc-integration-amq-streams:9092
      parsers:
      - ndjson:
          document_id: ircc.uniqueIdentifier
          expand_keys: true
          keys_under_root: true
          overwrite_keys: true
      topics:
      - ircc-integration-events
      type: kafka
    output:
      elasticsearch:
        hosts:
        - TO PATCH
        index: ircc-integration-container-logs
        indices:
        - index: ircc-integration-events
          when.has_fields:
          - ircc
          - ecs
        password: logger.elastic
        ssl.verification_mode: none
        username: logger
    setup:
      ilm.enabled: false
      template:
        name: filebeat
        pattern: filebeat*
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
          volumeMounts:
          - mountPath: /var/log/containers
            name: varlogcontainers
          - mountPath: /var/log/pods
            name: varlogpods
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        serviceAccountName: filebeat-ircc-dev
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /var/log/containers
          name: varlogcontainers
        - hostPath:
            path: /var/log/pods
          name: varlogpods
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
  type: filebeat
  version: 7.16.0