kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- elasticsearch-service-account.yaml
- heartbeat-service-account.yaml
- filebeat-service-account.yaml
- elasticsearch.yaml
- kibana.yaml
- apm-server.yaml